version: '2'

volumes:
  sqlite-data:
    driver: 'local'
  # postgres-data:
  #   driver: 'local'

services:
  notify:
    build: notify
    volumes:
      - ./notify:/usr/src/qkbot/notify
      - sqlite-data:/var/lib/qkbot
      - ./.env:/usr/src/qkbot/.env
    command: ruby /usr/src/qkbot/notify/notify.rb
  
  commandbot:
    build: commandbot
    volumes:
      - ./commandbot:/usr/src/qkbot/commandbot
      - ./.env:/usr/src/qkbot/.env
    command: ruby /usr/src/qkbot/commandbot/bot.rb

  # postgres:
  #   image: postgres:9.3
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  