# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'nokogiri', '~> 1.8.2'
gem 'unicode', '~> 0.4.4.4'
gem 'sqlite3', '~> 1.3.13'
gem 'dotenv', '~> 2.2.1'
